#!/bin/bash

if [ $# -eq 0 ] ;then
    echo "No parameter passed"
    exit 2
fi

number=$#
param=`echo $@`

for i in $param
do

    if [ ! -f $i ]; then
        echo "file does not exists. backup failed"
    else
        cp -iv ${i} ${i}_$(date +%Y%m%d%H%M%S)
    fi
done

